-- PostgreSQL schema for importing the espionage dataset
-- Derived from legacy SQLite schemas in legacy-schemas/

CREATE TABLE IF NOT EXISTS espionage_agents (
    AgentID TEXT PRIMARY KEY,
    SecretHandshakeQuality REAL,
    AccentThickness REAL,
    AgentStatus TEXT
);

CREATE TABLE IF NOT EXISTS espionage_splits (
    split_id INTEGER,
    AgentID TEXT REFERENCES espionage_agents(AgentID),
    holdout BOOLEAN NOT NULL DEFAULT FALSE,
    validation BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (split_id, AgentID)
);


CREATE TABLE IF NOT EXISTS espionage_rounds (
    round_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    split_id INTEGER,
    prompt TEXT,
    reasoning_for_this_prompt TEXT,
    stderr_from_prompt_creation TEXT,
    investigation_id INTEGER REFERENCES investigations(id)
);

CREATE TABLE IF NOT EXISTS espionage_inferences (
    round_id INTEGER REFERENCES espionage_rounds(round_id),
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AgentID TEXT REFERENCES espionage_agents(AgentID),
    narrative_text TEXT,
    llm_stderr TEXT,
    prediction TEXT,
    investigation_id INTEGER REFERENCES investigations(id),
    PRIMARY KEY (round_id, AgentID)
);
