-- PostgreSQL schema for importing the potions dataset
-- Derived from legacy SQLite schemas in legacy-schemas/

CREATE TABLE IF NOT EXISTS magic_potions (
    PotionBatchID TEXT PRIMARY KEY,
    FizzIntensity REAL,
    ColourShift REAL,
    PotionEffectiveness TEXT
);

CREATE TABLE IF NOT EXISTS potion_splits (
    split_id INTEGER,
    PotionBatchID TEXT REFERENCES magic_potions(PotionBatchID),
    holdout BOOLEAN NOT NULL DEFAULT FALSE,
    validation BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (split_id, PotionBatchID)
);


CREATE TABLE IF NOT EXISTS potions_rounds (
    round_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_uuid UUID DEFAULT gen_random_uuid(),
    round_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    split_id INTEGER,
    prompt TEXT,
    reasoning_for_this_prompt TEXT,
    stderr_from_prompt_creation TEXT,
    train_accuracy DOUBLE PRECISION,
    validation_accuracy DOUBLE PRECISION,
    test_accuracy DOUBLE PRECISION,
    round_completed TIMESTAMP,
    investigation_id INTEGER REFERENCES investigations(id)
);

CREATE TABLE IF NOT EXISTS potions_inferences (
    round_id INTEGER REFERENCES potions_rounds(round_id),
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PotionBatchID TEXT REFERENCES magic_potions(PotionBatchID),
    narrative_text TEXT,
    llm_stderr TEXT,
    prediction TEXT,
    investigation_id INTEGER REFERENCES investigations(id),
    PRIMARY KEY (round_id, PotionBatchID)
);
