-- PostgreSQL schema for importing the southgermancredit dataset
-- Derived from legacy SQLite schemas in legacy-schemas/

CREATE TABLE IF NOT EXISTS coral_reefs (
    decodex INTEGER,
    CoralReefID TEXT PRIMARY KEY,
    CurrentFlowQuality TEXT,
    ObservationDuration TEXT,
    ReefIntegrityScore TEXT,
    PredatorActivityLevel TEXT,
    AcousticIntensity TEXT,
    AlgalCoverage TEXT,
    CoralAgeEstimate TEXT,
    BleachingEventsPerYear TEXT,
    BiodiversityIndex TEXT,
    NearbyHealthyReef TEXT,
    ReefMonitoringDuration TEXT,
    PollutionLevel TEXT,
    ReefAverageAge TEXT,
    DistantStressIndicators TEXT,
    ReefDepthZone TEXT,
    PreviousStressIncidents TEXT,
    CoralDominantType TEXT,
    SurveyorExperience TEXT,
    RemoteSensorPresent TEXT,
    InvasiveSpeciesDetected TEXT,
    ReefHealthStatus TEXT
);

CREATE TABLE IF NOT EXISTS coral_reef_splits (
    split_id INTEGER,
    CoralReefID TEXT REFERENCES coral_reefs(CoralReefID),
    holdout BOOLEAN NOT NULL DEFAULT FALSE,
    validation BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (split_id, CoralReefID)
);


CREATE TABLE IF NOT EXISTS southgermancredit_rounds (
    round_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    split_id INTEGER,
    prompt TEXT,
    reasoning_for_this_prompt TEXT,
    stderr_from_prompt_creation TEXT,
    investigation_id INTEGER REFERENCES investigations(id)
);

CREATE TABLE IF NOT EXISTS southgermancredit_inferences (
    round_id INTEGER REFERENCES southgermancredit_rounds(round_id),
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CoralReefID TEXT REFERENCES coral_reefs(CoralReefID),
    narrative_text TEXT,
    llm_stderr TEXT,
    prediction TEXT,
    investigation_id INTEGER REFERENCES investigations(id),
    PRIMARY KEY (round_id, CoralReefID)
);
