-- PostgreSQL schema for importing the timetravel_insurance dataset
-- Derived from legacy SQLite schemas in legacy-schemas/

CREATE TABLE IF NOT EXISTS time_travel_incidents (
    IncidentID TEXT PRIMARY KEY,
    TimelineDeviation REAL,
    ParadoxCount REAL,
    PolicyClaim TEXT
);

CREATE TABLE IF NOT EXISTS time_travel_splits (
    split_id INTEGER,
    IncidentID TEXT REFERENCES time_travel_incidents(IncidentID),
    holdout BOOLEAN NOT NULL DEFAULT FALSE,
    validation BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (split_id, IncidentID)
);


CREATE TABLE IF NOT EXISTS timetravel_insurance_rounds (
    round_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_uuid UUID DEFAULT gen_random_uuid(),
    round_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    split_id INTEGER,
    prompt TEXT,
    reasoning_for_this_prompt TEXT,
    stderr_from_prompt_creation TEXT,
    train_accuracy DOUBLE PRECISION,
    validation_accuracy DOUBLE PRECISION,
    test_accuracy DOUBLE PRECISION,
    round_completed TIMESTAMP,
    investigation_id INTEGER REFERENCES investigations(id)
);

CREATE TABLE IF NOT EXISTS timetravel_insurance_inferences (
    round_id INTEGER REFERENCES timetravel_insurance_rounds(round_id),
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IncidentID TEXT REFERENCES time_travel_incidents(IncidentID),
    narrative_text TEXT,
    llm_stderr TEXT,
    prediction TEXT,
    investigation_id INTEGER REFERENCES investigations(id),
    PRIMARY KEY (round_id, IncidentID)
);
