-- PostgreSQL schema for importing the titanic dataset
-- Derived from legacy SQLite schemas in legacy-schemas/

CREATE TABLE IF NOT EXISTS patients (
    Patient_ID TEXT PRIMARY KEY,
    Decodex INTEGER,
    Outcome TEXT,
    Treatment_Group TEXT,
    Sex TEXT,
    Treatment_Months REAL,
    Genetic_Class_A_Matches INTEGER,
    Genetic_Class_B_Matches INTEGER,
    TcQ_mass REAL,
    Cohort TEXT
);

CREATE TABLE IF NOT EXISTS patient_splits (
    split_id INTEGER,
    patient_id TEXT REFERENCES patients(Patient_ID),
    holdout BOOLEAN NOT NULL DEFAULT FALSE,
    validation BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (split_id, patient_id)
);


CREATE TABLE IF NOT EXISTS titanic_rounds (
    round_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    split_id INTEGER,
    prompt TEXT,
    reasoning_for_this_prompt TEXT,
    stderr_from_prompt_creation TEXT,
    train_accuracy DOUBLE PRECISION,
    validation_accuracy DOUBLE PRECISION,
    test_accuracy DOUBLE PRECISION,
    round_completed TIMESTAMP,
    investigation_id INTEGER REFERENCES investigations(id)
);

CREATE TABLE IF NOT EXISTS titanic_inferences (
    round_id INTEGER REFERENCES titanic_rounds(round_id),
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    patient_id TEXT REFERENCES patients(Patient_ID),
    narrative_text TEXT,
    llm_stderr TEXT,
    prediction TEXT,
    investigation_id INTEGER REFERENCES investigations(id),
    PRIMARY KEY (round_id, patient_id)
);
