-- PostgreSQL schema for importing the wisconsin dataset
-- Derived from legacy SQLite schemas in legacy-schemas/

CREATE TABLE IF NOT EXISTS exoplanets (
    decodex INTEGER,
    exoplanet_id TEXT PRIMARY KEY,
    mean_orbital_radius TEXT,
    mean_surface_roughness TEXT,
    mean_magnetosphere_extent TEXT,
    mean_atmospheric_depth TEXT,
    mean_tidal_distortion TEXT,
    mean_core_density TEXT,
    mean_ring_system_complexity TEXT,
    mean_impact_crater_count TEXT,
    mean_axial_symmetry TEXT,
    mean_cloud_turbulence TEXT,
    orbital_radius_error TEXT,
    surface_roughness_error TEXT,
    magnetosphere_extent_error TEXT,
    atmospheric_depth_error TEXT,
    tidal_distortion_error TEXT,
    core_density_error TEXT,
    ring_system_complexity_error TEXT,
    impact_crater_count_error TEXT,
    axial_symmetry_error TEXT,
    cloud_turbulence_error TEXT,
    max_orbital_radius TEXT,
    max_surface_roughness TEXT,
    max_magnetosphere_extent TEXT,
    max_atmospheric_depth TEXT,
    max_tidal_distortion TEXT,
    max_core_density TEXT,
    max_ring_system_complexity TEXT,
    max_impact_crater_count TEXT,
    max_axial_symmetry TEXT,
    max_cloud_turbulence TEXT,
    occupying_species TEXT
);

CREATE TABLE IF NOT EXISTS exoplanet_splits (
    split_id INTEGER,
    exoplanet_id TEXT REFERENCES exoplanets(exoplanet_id),
    holdout BOOLEAN NOT NULL DEFAULT FALSE,
    validation BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (split_id, exoplanet_id)
);


CREATE TABLE IF NOT EXISTS wisconsin_rounds (
    round_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    split_id INTEGER,
    prompt TEXT,
    reasoning_for_this_prompt TEXT,
    stderr_from_prompt_creation TEXT,
    train_accuracy DOUBLE PRECISION,
    validation_accuracy DOUBLE PRECISION,
    test_accuracy DOUBLE PRECISION,
    round_completed TIMESTAMP,
    investigation_id INTEGER REFERENCES investigations(id)
);

CREATE TABLE IF NOT EXISTS wisconsin_inferences (
    round_id INTEGER REFERENCES wisconsin_rounds(round_id),
    creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    exoplanet_id TEXT REFERENCES exoplanets(exoplanet_id),
    narrative_text TEXT,
    llm_stderr TEXT,
    prediction TEXT,
    investigation_id INTEGER REFERENCES investigations(id),
    PRIMARY KEY (round_id, exoplanet_id)
);
