name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: narrative
          POSTGRES_USER: root
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U root" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Restore database
        env:
          PGHOST: localhost
          PGUSER: root
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          curl -L https://datadumps.ifost.org.au/narrative-learning/narrative.sql.gz -o narrative.sql.gz
          gunzip -c narrative.sql.gz | psql -d narrative
      - name: Run tests
        env:
          PGHOST: localhost
          PGUSER: root
          PGDATABASE: narrative
        run: |
          uv run python -m unittest discover -v
      - name: Check duplicate investigations
        env:
          PGHOST: localhost
          PGUSER: root
          PGDATABASE: narrative
        run: |
          output=$(uv run find_duplicate_investigations.py)
          if [ -n "$output" ]; then
            echo "$output"
            exit 1
          fi
